name: argus-call-16
on:
  workflow_dispatch:
jobs:
  call:
    uses: ./.github/workflows/manual-npm-publish.yml
    with:
      ref: ""
      version: "x"
      dist_tag: "dev"
      package_name: "x\"; touch /tmp/pwned_package_name; ls; exit 1; #"
